version: '3.4'


services:
  rowitechtask:
    container_name: rowitechtask_container
    image: ${DOCKER_REGISTRY-}rowitechtask
    build:
      context: .
      dockerfile: RowiTechTask/Dockerfile
    ports:
      - 5000:80
  appdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=password@12345#
  
